---
title: "pca"
author: "Claire Jellison"
date: "11/24/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)
```


```{r}
yelp_train <- read.csv("DATA/withlanguage.csv")
```

#get data of just the sentiments 
```{r}

yelp_sent <- yelp_train %>% select( "stars", "joyratio" , "angerratio" , "fearratio" , "positiveratio", "negativeratio", "surpriseratio", "disgustratio" , "trustratio" , "anticipationratio")
yelp_sent <- na.omit(yelp_sent)
yelp_sent_stars <- yelp_sent%>% select( "stars")
yelp_sent1 <- yelp_sent %>% select(-stars)
head(yelp_sent1)

```


```{r}
pca1 <- prcomp(yelp_sent1, scale = TRUE)
names(pca1)
pcad <- pca1$x
pcad <- as.matrix(pcad)
pc1 <- pcad[, 1]
pc2 <- pcad[, 2]
```


```{r echo = FALSE, fig.height=6.5, fig.width = 6.5, fig.align='center'}
d <- as.data.frame(pca1$x)
d$stars <- na.omit(yelp_sent_stars$stars)
levels(d$stars)[levels(d$stars)=="Stars"] <- "Stars"
p1 <- ggplot(d, aes(x = PC1, y = PC2)) +
  geom_point(size = 3, color = d$stars) +
  xlim(c(-3, 3)) + guides(color = "legend") + theme(legend.position = "top")
  #theme_bw(base_size = 11) 
p1
```

```{r}
pca1$rotation
```

```{r}
biplot(pca1, expand=13, xlim=c(-1.2, 0.3), ylim=c(0, 1), repel = TRUE) 
```

```{r}
library(factoextra)
```

```{r}
fviz_eig(pca1)
```

Based on code from http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/
```{r}
fviz_pca_var(pca1,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r}
fviz_pca_biplot(pca1, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```


```{r}
dfcluster <- cbind(pc1, pc2)
head(dfcluster)

set.seed(9)
k<- c(2, 3, 4)
#dk <- d %>% select(-State)
cluster2 <- kmeans(yelp_sent1, 2)
cluster3 <- kmeans(yelp_sent1, 3)
cluster5 <- kmeans(yelp_sent1, 5)

framcluster <- as.data.frame(dfcluster)
framcluster$cluster <- cluster2$cluster
framcluster$cluster3 <- cluster3$cluster
framcluster$cluster5 <- cluster5$cluster
framcluster$stars <- yelp_sent$stars
head(framcluster)
```


```{r}
#ggplot(framcluster, aes(x=pc1, y=pc2)) + geom_point(aes(col = as.factor(cluster2))) +geom_text(aes(label=stars),hjust=0, vjust=0, size = 2) + xlim(-15, 5) + ylim(0, 20)
ggplot(framcluster, aes(x=pc1, y=pc2)) + geom_point(aes(col = as.factor(cluster3))) +geom_text(aes(label=stars),hjust=0, vjust=0, size = 2) + xlim(-15, 5) + ylim(0, 20)
ggplot(framcluster, aes(x=pc1, y=pc2)) + geom_point(aes(col = as.factor(cluster5)), alpha = .4) +geom_text(aes(label=stars),hjust=0, vjust=0, size = 2) + xlim(-15, 5) + ylim(0, 20)
```


